name: gleam4_paper
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas=2.2.*
  - xarray=2024.09.0
  - netCDF4
  - seaborn=0.13.*
  - ipykernel
  - cftime
  - pip
  - pip:
    - zenodo-get 